### PR TITLE
Fix more occurrences of encodestring/decodestring

### LINKED ISSUE #1118: Encountered an error on Python 3.9 - AttributeError: module 'base64' has no attribute 'decodestring'
Microsoft's app center has recently updated to Python 3.9, and I encountered the follow error when running gsutil on it:

```
Traceback (most recent call last):
  File "/usr/local/bin/gsutil", line 5, in <module>
    from gslib.__main__ import main
  File "/usr/local/lib/python3.9/site-packages/gslib/__main__.py", line 92, in <module>
    from gslib.command_runner import CommandRunner
  File "/usr/local/lib/python3.9/site-packages/gslib/command_runner.py", line 64, in <module>
    from gslib.tests.util import HAS_NON_DEFAULT_GS_HOST
  File "/usr/local/lib/python3.9/site-packages/gslib/tests/util.py", line 126, in <module>
    TEST_ENCRYPTION_KEY1_SHA256_B64 = Base64Sha256FromBase64EncryptionKey(
  File "/usr/local/lib/python3.9/site-packages/gslib/utils/encryption_helper.py", line 152, in Base64Sha256FromBase64EncryptionKey
    decoded_bytes = base64.decodestring(csek_encryption_key)
AttributeError: module 'base64' has no attribute 'decodestring'
```

This error is triggered with `gsutil -o Credentials:gs_service_key_file=./mykey.json cp src_url dist_url` command.

Any thoughts on how to get this command work on Python 3.9? Thank you.

### PR DESCRIPTION
**Pull request by rrauber**
Looks like I missed a few in #1129. I confirmed that our tests pass with Python 3.9, so this should fix #1118.

### CODE REVIEW

**Comment by NickGoog** [comment]
Do we want to turn this `if six.PY2` logic into a util somewhere?

**Comment by rrauber** [comment]
> Do we want to turn this `if six.PY2` logic into a util somewhere?

Looks like base64.b64encode/decode is actually what we should be using. I switched to that everywhere except tests, to make sure they are actually the same.

**Review by NickGoog — APPROVED** [review]
hurrah for built-ins
