### ISSUE TITLE
Python 3.10 -- AttributeError: module 'collections' has no attribute 'Mapping' 

### ISSUE THREAD

**Issue by lukatendai** [GoogleCloudPlatform/gsutil#1331]
Traceback (most recent call last):
  File "/usr/lib64/google-cloud-sdk/bin/bootstrapping/gsutil.py", line 15, in <module>
    import bootstrapping
  File "/usr/lib64/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 46, in <module>
    from googlecloudsdk.core.updater import update_manager
  File "/usr/lib64/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 39, in <module>
    from googlecloudsdk.core.console import progress_tracker
  File "/usr/lib64/google-cloud-sdk/lib/googlecloudsdk/core/console/progress_tracker.py", line 651, in <module>
    class _BaseStagedProgressTracker(collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'

**Comment by dconatha** [comment]
I've filed a case with gcp for this.  The official documentation *does* say that "python 3 is supported but 3.7 is recommended" here: https://cloud.google.com/storage/docs/gsutil_install#install

In the meantime, a nice workaround is to create a Python 3.7 environment (e.g. using pyenv) and setting the `CLOUDSDK_PYTHON` environment variable to the 3.7 version of python.

**Comment by lukatendai** [comment]
yes, i used CLOUDSDK_PYTHON and it works, I submitted this issue because fedora 35 comes with Python 3.10 and after the upgrade gsutil stops working

**Comment by transacid** [comment]
```
$ grep -A3 '_py3_interpreter_compat_with_gsutil' /usr/lib64/google-cloud-sdk/bin/gcloud
_py3_interpreter_compat_with_gsutil () {​​​​​​​​​
  # Some environments (e.g. macOS) don't support grep -P, so we use grep -E.
  echo "$("$1" -V 2>&1)" | grep -E "Python 3[.]([5-9]|[1-9][0-9])" > /dev/null
}​​​​​​​​​
$ python3 -c 'import sys; print(sys.version)' | grep -E "Python 3[.]([5-9]|[1-9][0-9])"
$ echo $?                                  
1
$ python3 -c 'import sys; print(sys.version)'              
3.10.0 (default, Oct  4 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
```

**Comment by Kyle-Symph** [comment]
Hi I am having the same issue as you, I'm having trouble to understand since I'm just a beginner with app engine/python, how do I specifically use the CLOUDSDK_PYTHON within my project, where do I type it should it be on my projects console or the google cloud sdk console? I have python 3.10 installed

**Comment by dconatha** [comment]
`CLOUDSDK_PYTHON` is an [environment variable](https://en.wikipedia.org/wiki/Environment_variable) that specifies which version of Python the `gsutil` utility uses, on your local machine.  You need to create a Python 3.7 environment (using conda, pyenv, etc. or just download/install it directly from https://www.python.org/downloads/) set `CLOUDSDK_PYTHON` to that version of Python (e.g. mine points to `~/.cloudsdk-python/.venv/bin/python`).  The easiest way to set it forever is to put it in your .bashrc or .zshrc file or whatever:

```
export CLOUDSDK_PYTHON=path/to/python3.7
```

This is all assuming unix/mac/linux... I no idea about windows.

**Comment by FirefighterBlu3** [comment]
This appears to be fixed in the current cloud sdk release. gsutil no longer exhibits this exception

**Comment by JSpiner** [comment]
```python
# For Python 3, gsutil requires Python 3.5+.
_py3_interpreter_compat_with_gsutil () {
  # Some environments (e.g. macOS) don't support grep -P, so we use grep -E.
  echo "$("$1" -V 2>&1)" | grep -E "Python 3[.]([5-9]|[1-9][0-9])" > /dev/null
}
```

There is an error in this regular expression in 'google-cloud-sdk/install.sh'.
This only allows from '3.5xx' to '3.9xx'.
But sadly Python 3.10 has been released.

**Comment by me-suzy** [comment]
THE SAME ERROR

```
>>> 
*** Remote Interpreter Reinitialized ***
Traceback (most recent call last):
  File "E:\Carte\BB\17 - Site Leadership\alte\Ionel Balauta\Aryeht\Task 1 - Traduce tot site-ul\Doar Google Web\Andreea\Meditatii\Sedinta 9 (2022) (EMAIL)\BEBE-PARSING-Python (fara redenumire 2).py", line 1, in <module>
    import requests
  File "C:\Users\Castel\AppData\Roaming\Python\Python310\site-packages\requests\__init__.py", line 63, in <module>
    from . import utils
  File "C:\Users\Castel\AppData\Roaming\Python\Python310\site-packages\requests\utils.py", line 27, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "C:\Users\Castel\AppData\Roaming\Python\Python310\site-packages\requests\cookies.py", line 172, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
>>> 
```

THis also highlights this line on the file cookies.py

class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):

**Comment by me-suzy** [comment]
THE SOLUTION: I resolve the problem by installing this:

install this:  [](https://pypi.org/project/uplink/)

**pip install uplink**

**Comment by shaneutt** [comment]
I see comments above mentioning this is fixed in the latest SDK but after downloading a new copy today this did not appear to be the case for me. On Arch Linux switching to `python2` worked for me.

```console
$ pacman -S python2
$ export CLOUDSDK_PYTHON="/bin/python2"
```

**Comment by snorremd** [comment]
Homebrew users can install python 3.7 along the latest install (i.e. `brew install python@3.7`) and use the `CLOUDSDK_PYTHON` variable as described above with `/usr/local/bin/python3.7` as the path.

**Comment by aliwaqas333** [comment]
for new version of python, use `collections.abc.Mapping`

**Comment by me-ydv-5** [comment]
using python version `3.8.13` seems to work for me.

**Comment by daleki** [comment]
> using python version `3.8.13` seems to work for me. doesn't work with `3.10.4`.

also still broken with Python 3.10.6

**Comment by paneq** [comment]
Just got hit with this as well.

```
$python3 --version
Python 3.10.6

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```

**Comment by katcipis** [comment]
Same error using Alpine Linux:

```
python3 --version
Python 3.10.12
```

Error:

```
Welcome to the Google Cloud SDK!
WARNING: You appear to be running this script as root. This may cause
the installation to be inaccessible to users other than the root user.
Traceback (most recent call last):
  File "/usr/local/lib/google-cloud-sdk/bin/bootstrapping/install.py", line 12, in <module>
    import bootstrapping
  File "/usr/local/lib/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 46, in <module>
    from googlecloudsdk.core.updater import update_manager
  File "/usr/local/lib/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 39, in <module>
    from googlecloudsdk.core.console import progress_tracker
  File "/usr/local/lib/google-cloud-sdk/lib/googlecloudsdk/core/console/progress_tracker.py", line 631, in <module>
    class _BaseStagedProgressTracker(collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'
```

**Comment by SkandaPrasad-S** [comment]
```
python rules.py
Traceback (most recent call last):
  File "C:\Users\Skanda\Desktop\mongostuff\Advent Of code\Testing\rules.py", line 1, in <module>
    from experta import *
  File "E:\Software\Lib\site-packages\experta\__init__.py", line 5, in <module>
    from .engine import KnowledgeEngine
  File "E:\Software\Lib\site-packages\experta\engine.py", line 13, in <module>
    from experta.fact import InitialFact
  File "E:\Software\Lib\site-packages\experta\fact.py", line 9, in <module>
    from experta.utils import freeze, unfreeze
  File "E:\Software\Lib\site-packages\experta\utils.py", line 4, in <module>
    from frozendict import frozendict
  File "E:\Software\Lib\site-packages\frozendict\__init__.py", line 16, in <module>
    class frozendict(collections.Mapping):
    
```
Same error here! with python 3.11.1

**Comment by cathychen-glean** [comment]
Same error for python 3.10!

**Comment by bdobry** [comment]
Had the same problem with python `3.11.4`. The fix for me was to do `export CLOUDSDK_PYTHON=/usr/local/bin/python3` and restarting

```
$ where python3
/usr/local/bin/python3

$ /usr/local/bin/python3 --version
Python 3.11.4

$ export CLOUDSDK_PYTHON=/usr/local/bin/python3
```

**Comment by MichaelSchmidt82** [comment]
I can confirm on an Ubuntu 22.04 docker image that adding
```
ENV CLOUDSDK_PYTHON "/usr/bin/python"
```
will work.  Ubuntu 22.04 uses Python 3.10 natively.

**Comment by jxc876** [comment]
I was getting this error because my Micronaut app scaffolded a Actions workflow with an old version of `setup-gcloud`.

It got fixed once I removed the `with.version:` parameter

**Comment by anuvedantham** [comment]
Encountering this issue on multiple python versions (3.9.15, 3.10.8, 3.11.0). `export CLOUDSDK_PYTHON=/location/of/python/version` is not succeeding for me

**Comment by gravelld** [comment]
Ubuntu 22.04. Google Cloud SDK 475.0.0 

I have been trying to start up using the Gradle plugin today but the cloud SDK JARs didn't seem to get downloaded.

After burying through the logs I found the problems was this command being run:

```
$ /myhome/cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/bin/gcloud components list --only-local-state --format=json --filter=id:app-engine-java
ERROR: gcloud failed to load: module 'collections' has no attribute 'MutableMapping'
    gcloud_main = _import_gcloud_main()
    import googlecloudsdk.gcloud_main
    from googlecloudsdk.api_lib.iamcredentials import util as iamcred_util
    from googlecloudsdk.api_lib.util import exceptions
    from googlecloudsdk.core.resource import resource_printer
    from googlecloudsdk.core.resource import config_printer
    from googlecloudsdk.core.resource import resource_printer_base
    from googlecloudsdk.core.resource import resource_projector
    from google.protobuf import json_format as protobuf_encoding
    __import__('pkg_resources').declare_namespace(__name__)
    import packaging.requirements
    from pyparsing import stringStart, stringEnd, originalTextFor, ParseException
    collections.MutableMapping.register(ParseResults)
```

If I set the python interpreter to 2.7 then it works to download the SDK, but, still, re-running the above command gave a new error:

```
ERROR: gcloud failed to load. You are running gcloud with Python 2.7, which is no longer supported by gcloud.
Install a compatible version of Python 3.8-3.12 and set the CLOUDSDK_PYTHON environment variable to point to it.
```

At that point I set the cleared the `CLOUDSDK_PYTHON` env variable so it was using Ubuntu's default 3.10 version again and the command executed successfully.
