### ISSUE TITLE
AttributeError: 'module' object has no attribute 'DoubleQuotedScalarString'

### ISSUE THREAD

**Issue by theSoenke** [GoogleCloudPlatform/gsutil#741]
When running `gsutil` I get the following error:

```
Traceback (most recent call last):
  File "bin/google-cloud-sdk/bin/bootstrapping/gsutil.py", line 13, in <module>
    import bootstrapping
  File "bin/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 46, in <module>
    from googlecloudsdk.core.updater import update_manager
  File "bin/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 35, in <module>
    from googlecloudsdk.core import yaml
  File "bin/google-cloud-sdk/lib/googlecloudsdk/core/yaml.py", line 29, in <module>
    from googlecloudsdk.core import yaml_location_value
  File "bin/google-cloud-sdk/lib/googlecloudsdk/core/yaml_location_value.py", line 60, in <module>
    class _LvDoubleQuotedScalarString(yaml.scalarstring.DoubleQuotedScalarString):  # pytype: disable=bad-slots
AttributeError: 'module' object has no attribute 'DoubleQuotedScalarString'
```

`python --version`              
Python 2.7.16

`gcloud version `         
Google Cloud SDK 241.0.0
alpha 2019.02.22
beta 2019.02.22
bq 2.0.43
core 2019.04.02
datalab 20190116
gsutil 4.38

I've also tried older versions of gcloud and it still worked in version `220.0.0` with gsutil 4.34  and broke in `221.0.0`

**Comment by houglum** [comment]
This is an issue with the Cloud SDK, not gsutil (which is packaged with the gcloud SDK).  Please open an issue [at this link](https://b.corp.google.com/issues/new?component=187143&template=800102) (the "Create new Cloud SDK issue" link at https://cloud.google.com/support/docs/issue-trackers).
