### ISSUE TITLE
Python 3.8 Time module does not contain clock

### ISSUE THREAD

**Issue by MeNsaaH** [GoogleCloudPlatform/gsutil#1127]
running `gsutil web get gs://bucket`

Throws Error:
```
module 'time' has no attribute 'clock'
```

**Comment by tirkarthi** [comment]
Can you please attach the full traceback?

**Comment by MeNsaaH** [comment]
That is the only error I get no traceback. I think it's handled

**Comment by MeNsaaH** [comment]
I'll be closing this issue. It seems to be a problem with my gsutil installation. Everything works fine now that I used the `apt` gcloud package.

**Comment by jbg** [comment]
Trying to use Google Cloud SDK with Python versions newer than 3.8 gives this error.

**Comment by MeNsaaH** [comment]
Check your installation @jbg. Maube try reinstalling

**Comment by jbg** [comment]
I have it working fine with Python 3.8, thanks. Was just pointing out one possible cause of this error for people who arrive here from a Google search (as I did).

**Comment by Wundark** [comment]
Using Python 3.8.10, time.clock() has now been removed and gsutil doesn't work.

```
root@box:/# python -V
Python 3.8.10
root@box:/# gsutil cp gs://data/* ./data/
module 'time' has no attribute 'clock'
```

**Comment by RunOrVeith** [comment]
Ok, so I found a work around / cause for this issue.
The culprit is that the library pycrypto that is installed with some distributions of gsutil is being called, and this calls time.clock.

If you make sure that you do NOT have pycrypto installed, but instead `pip install pycryptodomex`, it will work again.

I have also found that this only happens if you invoke gsutil rsync using a service account for authorization (`GOOGLE_APPLICATION_CREDENTIALS=...` or `gcloud auth activate-service-account --key-file ...`) .
If you use a regular user account with OAuth2, it will not happen (which makes this issue quite hard to debug, because you have to figure that out before you can reproduce it locally).

This also only happens if you installed gsutil as a component of gcloud. If you used pip (`pip install gsutil`), you will not have that issue.

So the solution is to basically do this. Example from a docker container:

```Dockerfile
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && apt-get update -y && apt-get install google-cloud-sdk -y
      
RUN pip uninstall pycrypto && pip install pycryptodomex
```
